93 backend course information bento
techstartucalgary/lifeline pull request #100
Opened 2023-02-09 04:25 UTC by cloudyyoung

2023-02-09 14:54 UTC, tim-macphail requested changes
Merge conflicts :/

2023-02-09 23:53 UTC, tim-macphail commented
Looks like routing is broken, clicking on courses won't show you the assessments or highlight the current course in the nav drawer. It also seems like the faculty name is being used in place of the course name/code
![image](https://user-images.githubusercontent.com/70448914/217964966-aeceb5ab-2266-49d4-b3d7-a7bcd0bd5798.png)

2023-02-10 00:05 UTC, cloudyyoung commented
> Looks like routing is broken, clicking on courses won't show you the assessments or highlight the current course in the nav drawer. It also seems like the faculty name is being used in place of the course name/code ![image](https://user-images.githubusercontent.com/70448914/217964966-aeceb5ab-2266-49d4-b3d7-a7bcd0bd5798.png)

A break in FE is expected, as the response strcuture is changed from the BE. This PR only contains changes in BE, and another PR for fixing the FE will be opened.

2023-02-10 02:18 UTC, tim-macphail approved these changes

2023-02-10 02:19 UTC, merged