Landing page done!
techstartucalgary/lifeline pull request #21
Opened 2022-11-26 23:22 UTC by BradleyLi

The landing page is finished except the footer. Please review my push request. Thanks!

2022-11-28 21:24 UTC, cloudyyoung requested changes
Further improvements are to be posted after #18 is merged :)

2022-11-28 21:24 UTC, cloudyyoung commented on server/tsconfig.json
> +{
This file should be gone.

2022-11-28 21:24 UTC, cloudyyoung commented on package.json
> +{
There shouldn't be a package.json file in the root directory (when mono-repo causes confusion 😅)

2022-11-28 21:24 UTC, cloudyyoung commented on postcss.config.js
> +module.exports = {
Same.

2022-11-28 21:24 UTC, cloudyyoung commented on package-lock.json
> +{
Same.

2022-11-28 21:24 UTC, cloudyyoung commented on tailwind.config.js
> +/** @type {import('tailwindcss').Config} */
Same.

2022-11-28 21:24 UTC, cloudyyoung commented on client/tailwind.config.js
> +        'start': '#B7194A'
This is not how extended color palette should be used (and class naming should be kabab-case)

2022-12-02 01:04 UTC, tim-macphail commented
It works!

2022-12-02 01:05 UTC, tim-macphail approved these changes
It's not perfect but that's fine, we can make it better in later PRs 😄

2022-12-02 21:35 UTC, jaza-k approved these changes

2022-12-05 17:45 UTC, merged