new pull request
techstartucalgary/lifeline pull request #24
Opened 2022-12-06 07:00 UTC by BradleyLi

Signed-off-by: Bradley <jizhe.li@ucalgary.cm>

2022-12-06 20:16 UTC, tim-macphail commented
This is a bit funky because I merged it too early then had you create a new branch. But looking through your files everything looks good, I see you resolved all the conversations that Yunfan started, and now that #18 is in this should be all good.
One thing: please delete the comment in lines 7-9 in Landing.tsx

2022-12-06 22:40 UTC, tim-macphail approved these changes
@jaza-k has plans to do some refactoring but I'm happy to put this into main for the time being 😀

2022-12-07 06:58 UTC, cloudyyoung commented on client/tailwind.config.js
> -          95: "#FFECED",
This branch probably has merge conflict with the main branch at some point, but the resolving here is bad.
This reverts every change from #18, removing all added colour palette and fonts.

2022-12-07 20:24 UTC, jaza-k requested changes
Agree with @cloudyyoung, conflicts weren't resolved properly here, undoing #18. I created a new branch ```jaza/fix-bradley-landing``` which addresses these conflicts for now and makes it compatible with main. Further refactoring will be done soon

2023-01-16 03:41 UTC, cloudyyoung commented
Closing this as #36 merged

2023-01-16 03:41 UTC, closed without merging