Adds backend support for multiple file upload
techstartucalgary/lifeline pull request #84
Opened 2023-02-01 18:16 UTC by harsweet

Allows multiple file upload and returns an array of extracted dates from the files

<img width="1411" alt="Screen Shot 2023-02-01 at 11 09 52 AM" src="https://user-images.githubusercontent.com/64262868/216127896-c0b36b3a-b73f-4ccc-a79d-e5df0622f39f.png">

```
{
  "file_texts": [
    {
      "course": "MATH 376",
      "topic": "unknown topic",
      "assessments": [
        {
          "name": "Quiz 11",
          "date": "2022-09-22T00:00:00.000000",
          "weight": "6%",
          "source": "Sep 22 2022"
        },
        {
          "name": "Quiz 22",
          "date": "2022-10-13T00:00:00.000000",
          "weight": "6%",
          "source": "Oct 13 2022"
        },
        {
          "name": "Quiz 33",
          "date": "2022-11-03T00:00:00.000000",
          "weight": "6%",
          "source": "Nov 03 2022"
        },
        {
          "name": "Midterm Test",
          "date": "2022-11-15T18:00:00.000000",
          "weight": "30%",
          "source": "Nov 15 2022 at 06:00 pm"
        },
        {
          "name": "Quiz 44",
          "date": "2022-11-24T00:00:00.000000",
          "weight": "6%",
          "source": "Nov 24 2022"
        },
        {
          "name": "Quiz 55",
          "date": "2022-12-06T00:00:00.000000",
          "weight": "6%",
          "source": "Dec 06 2022"
        },
        {
          "name": "Midterm Test",
          "date": "2022-11-15T18:00:00.000000",
          "weight": "unknown",
          "source": "Tuesday, November 15, 2022 at 6:00 pm"
        }
      ]
    },
    {
      "course": "CPSC 583",
      "topic": "unknown topic",
      "assessments": [
        {
          "name": "Group Project1",
          "date": "2023-04-12T00:00:00.000000",
          "weight": "35%",
          "source": "Apr 12 2023"
        }
      ]
    },
    {
      "course": "ARTS",
      "topic": "unknown topic",
      "assessments": [
        {
          "name": "Email communication:",
          "date": "2023-01-30T11:09:32.948532",
          "weight": "unknown",
          "source": "48 hours"
        },
        {
          "name": "Day(s), time(s) and location \nof class:",
          "date": "2023-02-02T09:00:00.000000",
          "weight": "unknown",
          "source": "Thu 9:00-11:45 am"
        },
        {
          "name": "Required Textbook:",
          "date": "2023-01-02T00:00:00.000000",
          "weight": "unknown",
          "source": "1 and 2"
        },
        {
          "name": "QUESTIONNAIRE",
          "date": "2023-05-10T00:00:00.000000",
          "weight": "10%",
          "source": "Tuesday, 10 May"
        },
        {
          "name": "LECTURE RESPONSES",
          "date": "2023-05-16T00:00:00.000000",
          "weight": "35%",
          "source": "Monday, 16 May"
        },
        {
          "name": "DIVERSITY EXPLORATION OF TEXTBOOK",
          "date": "2023-05-16T00:00:00.000000",
          "weight": "25%",
          "source": "Monday, 16 May"
        },
        {
          "name": "CONCEPT MAP",
          "date": "2023-06-02T00:00:00.000000",
          "weight": "20%",
          "source": "Thursday, 2 June"
        },
        {
          "name": "FINAL REFLECTION",
          "date": "2023-06-16T00:00:00.000000",
          "weight": "10%",
          "source": "Thursday, 16 June"
        },
        {
          "name": "Assessment expectations:",
          "date": "2023-01-31T11:09:32.994460",
          "weight": "unknown",
          "source": "one day"
        },
        {
          "name": "Last day to drop course without financial penalty",
          "date": "2023-05-09T00:00:00.000000",
          "weight": "unknown",
          "source": "Monday, May 9"
        },
        {
          "name": "End of refund period",
          "date": "2023-05-09T00:00:00.000000",
          "weight": "unknown",
          "source": "Monday, May 9"
        },
        {
          "name": "Last day to add/swap course",
          "date": "2023-05-09T00:00:00.000000",
          "weight": "unknown",
          "source": "Monday, May 9"
        },
        {
          "name": "Tuition and fee payment deadline",
          "date": "2023-05-11T00:00:00.000000",
          "weight": "unknown",
          "source": "Wednesday, May 11"
        },
        {
          "name": "Last day to withdraw from course",
          "date": "2023-06-16T00:00:00.000000",
          "weight": "unknown",
          "source": "Thursday, June 16"
        },
        {
          "name": "Internet and electronic \ncommunication device:",
          "date": "2023-05-01T00:00:00.000000",
          "weight": "unknown",
          "source": "at may"
        }
      ]
    }
  ]
}
```

2023-02-01 21:59 UTC, tim-macphail approved these changes

2023-02-02 17:08 UTC, tim-macphail requested changes
See suggestions on app.py

2023-02-03 00:54 UTC, harsweet commented on server/app.py
> +async def send_outline_file(outline_files: List[UploadFile] = File(...)):
Agree!

2023-02-03 01:03 UTC, tim-macphail approved these changes

2023-02-03 01:51 UTC, skilledd007 approved these changes

2023-02-03 01:51 UTC, merged