Stripping newline character from assesment
techstartucalgary/lifeline pull request #86
Opened 2023-02-03 01:00 UTC by alisha-nas

Removed the newline character for better formatting

2023-02-03 03:47 UTC, cloudyyoung commented on README.md
> +<<<<<<< HEAD
This seems to be an unresolved conflict

2023-02-03 06:01 UTC, skilledd007 requested changes

2023-02-03 06:01 UTC, skilledd007 commented on README.md
> +<<<<<<< HEAD
Yep.

2023-02-03 15:08 UTC, tim-macphail requested changes
Looks like a bunch of extra files were created somehow. All we really care about is the changes in file_handler.py so you can go ahead and delete all the files with 2 in the name, add, commit, push again and it will update this pull request (make sure you're on this branch)

2023-02-03 15:08 UTC, tim-macphail commented on .gitattributes 2
> +*.pdf filter=lfs diff=lfs merge=lfs -text
duplicate file can be deleted

2023-02-05 17:48 UTC, tim-macphail approved these changes

2023-02-05 17:49 UTC, tim-macphail approved these changes

2023-02-08 08:45 UTC, cloudyyoung approved these changes

2023-02-09 02:54 UTC, merged